# Generated by Django 5.0.4 on 2024-04-22 05:26

import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('type', models.CharField(choices=[('LEAD', 'lead'), ('PROSPECT', 'prospect'), ('CUSTOMER', 'customer')], max_length=8)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_prospect', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('prospect_status', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed'), ('SUCCESS', 'success')], max_length=7, null=True)),
                ('customer_status', models.CharField(choices=[('ACTIVE', 'active'), ('ARCHIVED', 'archived')], max_length=8, null=True)),
                ('address', models.TextField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='contacts/', validators=[utils.validators.validate_file_size])),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.contact',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.contact',),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.contact',),
        ),
    ]
