from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.TestView.as_view(), name='test'),
    path('toast/', views.ToastView.as_view(), name='toast'),
    path('contact/<int:pk>/detail/',
         views.ContactDetailView.as_view(), name='contact-detail'),
    path('lead-create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('leads/', views.LeadListView.as_view(), name='lead-list'),
    # path('lead/<int:pk>/detail/',
    #      views.ContactDetailView.as_view(), name='lead-detail'),
    path('lead/<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead-update'),
    path('lead/<int:pk>/delete/', views.lead_soft_delete_view,
         name='lead-soft-delete'),
    # path('lead/<int:pk>/delete/', views.LeadDeleteView.as_view, name='lead-delete'),
    path('lead/<int:pk>/promote/', views.lead_promote_view, name='lead-promote'),
    path('prospect-create/', views.ProspectCreateView.as_view(),
         name='prospect-create'),
    path('prospects/', views.ProspectListView.as_view(), name='prospect-list'),
    # path('prospect/<int:pk>/detail/',
    #      views.ProspectDetailView.as_view(), name='prospect-detail'),
    path('prospect/<int:pk>/update/',
         views.ProspectUpdateView.as_view(), name='prospect-update'),
    path('prospect/<int:pk>/delete/',
         views.prospect_soft_delete_view, name='prospect-soft-delete'),
    # path('prospect/<int:pk>/delete/', views.ProspectDeleteView.as_view, name='prospect-delete'),
    path('prospect/<int:pk>/promote/',
         views.prospect_promote_view, name='prospect-promote'),
    path('customer-create/', views.CustomerCreateView.as_view(),
         name='customer-create'),
    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    # path('customer/<int:pk>/detail/',
    #      views.ContactDetailView.as_view(), name='customer-detail'),
    path('customer/<int:pk>/update/',
         views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete/',
         views.customer_soft_delete_view, name='customer-soft-delete'),
    # path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view, name='customer-delete'),
]
