# Generated by Django 5.0.4 on 2024-04-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('CREATE_CONTACT', 'create_contact'), ('UPDATE_CONTACT', 'update_contact'), ('SOFT_DELETE_CONTACT', 'soft_delete_contact'), ('DELETE_CONTACT', 'delete_contact'), ('PROMOTE_CONTACT', 'promote_contact'), ('CLOSE_PROSPECT', 'close_prospect'), ('ARCHIVE_CUSTOMER', 'archive_customer'), ('ALLOCATE_AGENT', 'allocate_agent'), ('CHANGE_AGENT', 'change_agent'), ('BULK_UPLOAD_CONTACT', 'bulk_upload_contact')], max_length=19)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
